route:
  receiver: 'default-receiver'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - receiver: 'email'
      matchers:
        - severity="email"
receivers:
  - name: 'email'
    email_configs:
      - to: john.r.swe@gmail.com
        from: no-reply@errors.err
        smarthost: smtp.gmail.com:587
  - name: 'default-receiver'
