host: 18.170.214.52
info:
  contact: {}
  description: Cruising' and Bruisin'
  title: Status API
  version: 0.1.0
paths:
  /status:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: get status
      tags:
      - noTag
swagger: "2.0"
